In [2]:
import torch

In [3]:
a = torch.rand(4, 1, 28, 28)

In [4]:
a.shape

torch.Size([4, 1, 28, 28])

In [5]:
a.view(4, 28*28)

tensor([[0.0407, 0.7126, 0.2743,  ..., 0.3248, 0.1242, 0.0362],
        [0.3159, 0.1511, 0.6496,  ..., 0.3998, 0.2799, 0.8600],
        [0.5032, 0.3137, 0.5733,  ..., 0.4375, 0.8257, 0.6726],
        [0.0233, 0.1505, 0.9582,  ..., 0.8599, 0.7399, 1.0000]])

In [6]:
a.view(4, 28*28).shape

torch.Size([4, 784])

In [7]:
a.view(4*28, 28).shape

torch.Size([112, 28])

In [8]:
b = a.view(4, 784)

In [9]:
b.view(4, 1, 28, 28)

tensor([[[[4.0743e-02, 7.1256e-01, 2.7431e-01,  ..., 9.9525e-01,
           4.6010e-01, 5.0155e-01],
          [8.6517e-01, 1.9909e-01, 8.2844e-01,  ..., 3.6030e-01,
           9.6641e-01, 4.2263e-01],
          [3.9410e-01, 7.8289e-01, 4.2571e-01,  ..., 9.3159e-01,
           4.2863e-01, 1.5793e-01],
          ...,
          [3.6026e-01, 7.9668e-01, 6.7036e-01,  ..., 4.5725e-01,
           2.3544e-02, 8.2025e-01],
          [4.5257e-01, 3.6902e-01, 3.4310e-01,  ..., 6.5075e-01,
           5.1082e-02, 5.0930e-01],
          [5.2419e-01, 1.5650e-01, 6.6277e-01,  ..., 3.2480e-01,
           1.2425e-01, 3.6214e-02]]],


        [[[3.1594e-01, 1.5109e-01, 6.4962e-01,  ..., 5.1206e-01,
           4.2768e-02, 7.1222e-01],
          [7.3800e-01, 5.9424e-01, 7.5259e-01,  ..., 3.5358e-02,
           6.1602e-01, 6.0571e-01],
          [2.3075e-01, 2.9577e-01, 9.9494e-01,  ..., 4.3055e-01,
           2.2124e-02, 1.2656e-01],
          ...,
          [6.7441e-01, 6.7198e-01, 2.6036e-01,  ..., 5.37

In [10]:
a.unsqueeze(0).shape

torch.Size([1, 4, 1, 28, 28])

In [11]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [13]:
a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [14]:
a =  torch.tensor([1.2, 2.3])

In [15]:
a.shape

torch.Size([2])

In [17]:
a.unsqueeze(-1),a.unsqueeze(-1).shape

(tensor([[1.2000],
         [2.3000]]), torch.Size([2, 1]))

In [18]:
a.unsqueeze(0),a.unsqueeze(0).shape

(tensor([[1.2000, 2.3000]]), torch.Size([1, 2]))

In [19]:
a = torch.rand(4, 32, 14, 14)

In [20]:
b = torch.rand(1, 32, 1, 1)

In [24]:
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [25]:
b.expand(-1, 32, -1, -1).shape # -1表示维度保持不变

torch.Size([1, 32, 1, 1])

In [26]:
b.expand(-1, 32, -1, -4).shape

torch.Size([1, 32, 1, -4])

In [27]:
b.repeat(4, 32, 1, 1).shape

torch.Size([4, 1024, 1, 1])

In [28]:
b.repeat(4, 1, 1, 1).shape

torch.Size([4, 32, 1, 1])

In [29]:
b.repeat(4, 1, 32, 32).shape

torch.Size([4, 32, 32, 32])

In [30]:
a = torch.randn(3, 4)

In [31]:
a.t()

tensor([[-1.3668,  1.9339,  0.8603],
        [ 0.1981,  2.4385,  2.1875],
        [ 0.5754,  0.1694, -0.0734],
        [-0.3411, -0.5878,  0.3197]])

In [32]:
b.t()

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D